// Productcatalogus — pas hier prijzen, categorieën en voorraad aan.
const CATEGORIES = [
  { id: "huishouden", name: "Huishouden", icon: "🧽" },
  { id: "wonen", name: "Wonen", icon: "🛋️" },
  { id: "keuken", name: "Keuken", icon: "🍳" },
  { id: "speelgoed", name: "Speelgoed", icon: "🧸" },
  { id: "hobby", name: "Hobby & creatief", icon: "🎨" },
  { id: "verzorging", name: "Verzorging", icon: "🧴" },
  { id: "tuin", name: "Tuin & buiten", icon: "🌱" },
  { id: "multimedia", name: "Multimedia", icon: "🔌" },
  { id: "snoep", name: "Snoep & drinken", icon: "🍬" },
  { id: "dieren", name: "Dieren", icon: "🐾" },
];

const PRODUCTS = [
  { id: 1, name: "Microvezeldoekjes 10 stuks", cat: "huishouden", price: 1.49, emoji: "🧽", color: "#dbeafe", rating: 4.6, reviews: 812, tag: "Bestseller" },
  { id: 2, name: "Allesreiniger citroen 1 L", cat: "huishouden", price: 0.89, emoji: "🧴", color: "#fef9c3", rating: 4.4, reviews: 356 },
  { id: 3, name: "Opvouwbare wasmand", cat: "huishouden", price: 3.95, old: 4.95, emoji: "🧺", color: "#e0e7ff", rating: 4.3, reviews: 147, deal: true },
  { id: 4, name: "Vuilniszakken 60 L, 20 stuks", cat: "huishouden", price: 1.29, emoji: "🗑️", color: "#e5e7eb", rating: 4.5, reviews: 590 },
  { id: 5, name: "Geurkaars vanille", cat: "wonen", price: 1.99, emoji: "🕯️", color: "#fde68a", rating: 4.7, reviews: 1203, tag: "Populair" },
  { id: 6, name: "Fotolijst 20×30 cm", cat: "wonen", price: 2.49, emoji: "🖼️", color: "#fce7f3", rating: 4.2, reviews: 221 },
  { id: 7, name: "Fleeceplaid 130×160 cm", cat: "wonen", price: 4.95, old: 6.95, emoji: "🛏️", color: "#ede9fe", rating: 4.8, reviews: 967, deal: true },
  { id: 8, name: "Kunstplant in pot", cat: "wonen", price: 3.49, emoji: "🪴", color: "#dcfce7", rating: 4.4, reviews: 412 },
  { id: 9, name: "LED-lichtsnoer 5 m", cat: "wonen", price: 2.99, emoji: "✨", color: "#fef3c7", rating: 4.5, reviews: 688 },
  { id: 10, name: "Pannenset anti-aanbak 3-delig", cat: "keuken", price: 14.95, old: 19.95, emoji: "🍳", color: "#fee2e2", rating: 4.3, reviews: 304, deal: true },
  { id: 11, name: "Vershoudbakjes 6 stuks", cat: "keuken", price: 2.79, emoji: "🥡", color: "#e0f2fe", rating: 4.6, reviews: 455 },
  { id: 12, name: "Siliconen spatel", cat: "keuken", price: 0.99, emoji: "🥄", color: "#ffedd5", rating: 4.5, reviews: 233 },
  { id: 13, name: "Koffiemok 'Goedemorgen'", cat: "keuken", price: 1.79, emoji: "☕", color: "#f5f5f4", rating: 4.1, reviews: 98 },
  { id: 14, name: "Bouwstenen 500 stuks", cat: "speelgoed", price: 7.95, emoji: "🧱", color: "#fee2e2", rating: 4.7, reviews: 781, tag: "Bestseller" },
  { id: 15, name: "Knuffelbeer 30 cm", cat: "speelgoed", price: 4.49, emoji: "🧸", color: "#fde68a", rating: 4.8, reviews: 522 },
  { id: 16, name: "Bellenblaas 3-pack", cat: "speelgoed", price: 1.19, emoji: "🫧", color: "#cffafe", rating: 4.2, reviews: 176 },
  { id: 17, name: "Puzzel 1000 stukjes", cat: "speelgoed", price: 3.95, old: 4.95, emoji: "🧩", color: "#dbeafe", rating: 4.6, reviews: 340, deal: true },
  { id: 18, name: "Acrylverf 12 kleuren", cat: "hobby", price: 3.29, emoji: "🎨", color: "#fae8ff", rating: 4.5, reviews: 612, tag: "Nieuw" },
  { id: 19, name: "Schetsboek A4", cat: "hobby", price: 1.99, emoji: "📓", color: "#f5f5f4", rating: 4.4, reviews: 287 },
  { id: 20, name: "Haakgaren 5 bollen", cat: "hobby", price: 4.49, emoji: "🧶", color: "#fce7f3", rating: 4.6, reviews: 198 },
  { id: 21, name: "Shampoo 300 ml", cat: "verzorging", price: 1.09, emoji: "🧴", color: "#d1fae5", rating: 4.3, reviews: 402 },
  { id: 22, name: "Tandenborstels 4 stuks", cat: "verzorging", price: 1.49, emoji: "🪥", color: "#e0f2fe", rating: 4.4, reviews: 266 },
  { id: 23, name: "Gezichtsmaskers 5-pack", cat: "verzorging", price: 2.25, old: 2.95, emoji: "💆", color: "#fdf2f8", rating: 4.2, reviews: 154, deal: true },
  { id: 24, name: "Tuinhandschoenen", cat: "tuin", price: 1.69, emoji: "🧤", color: "#dcfce7", rating: 4.3, reviews: 133 },
  { id: 25, name: "Solar tuinlamp", cat: "tuin", price: 2.49, emoji: "💡", color: "#fef9c3", rating: 4.1, reviews: 455 },
  { id: 26, name: "Bloempot terracotta Ø20", cat: "tuin", price: 2.99, emoji: "🌱", color: "#ffedd5", rating: 4.5, reviews: 189 },
  { id: 27, name: "USB-C kabel 1 m", cat: "multimedia", price: 1.99, emoji: "🔌", color: "#e5e7eb", rating: 4.2, reviews: 734 },
  { id: 28, name: "Draadloze oordopjes", cat: "multimedia", price: 12.95, old: 14.95, emoji: "🎧", color: "#e0e7ff", rating: 4.0, reviews: 921, deal: true },
  { id: 29, name: "Powerbank 10.000 mAh", cat: "multimedia", price: 9.95, emoji: "🔋", color: "#dbeafe", rating: 4.4, reviews: 568, tag: "Populair" },
  { id: 30, name: "Chocoladerepen 3-pack", cat: "snoep", price: 1.59, emoji: "🍫", color: "#fde68a", rating: 4.7, reviews: 310 },
  { id: 31, name: "Zure matten 400 g", cat: "snoep", price: 1.25, emoji: "🍬", color: "#fce7f3", rating: 4.6, reviews: 277 },
  { id: 32, name: "Energiedrank 4 blikjes", cat: "snoep", price: 2.29, emoji: "🥤", color: "#cffafe", rating: 4.1, reviews: 145 },
  { id: 33, name: "Kattenspeeltje met veer", cat: "dieren", price: 0.99, emoji: "🐱", color: "#fef3c7", rating: 4.5, reviews: 218 },
  { id: 34, name: "Hondenmand 60 cm", cat: "dieren", price: 9.95, old: 12.95, emoji: "🐶", color: "#ede9fe", rating: 4.6, reviews: 402, deal: true },
  { id: 35, name: "Kauwbotjes 10 stuks", cat: "dieren", price: 1.89, emoji: "🦴", color: "#ffedd5", rating: 4.4, reviews: 189 },
  { id: 36, name: "Opbergbox 30 L met deksel", cat: "huishouden", price: 4.49, emoji: "📦", color: "#e0f2fe", rating: 4.7, reviews: 1044, tag: "Bestseller" },
];
